### ISSUE TITLE
How to use curl?

### ISSUE THREAD

**Issue by BassemN** [ADmad/cakephp-social-auth#46]
Hello,

How to configure the plugin to use curl? because most of my clients their servers have `allow_url_fopen=0`

Thanks

**Comment by ADmad** [comment]
The plugin uses Cake's Http Client which uses socket and doesn't require `allow_url_fopen`.

**Comment by BassemN** [comment]
but why I get this error after coming from google
```
2018-06-05 11:33:04 Error: [Cake\Core\Exception\Exception] fopen(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0
fopen(https://accounts.google.com/o/oauth2/token): failed to open stream: no suitable wrapper could be found
Request URL: /social-auth/callback/google/?state=StateRemoved&code=CodeRemoved
Stack Trace:
#0 /vendor/cakephp/cakephp/src/Http/Client/Adapter/Stream.php(252): Cake\Http\Client\Adapter\Stream->_open(Object(Zend\Diactoros\Uri))
#1 /vendor/cakephp/cakephp/src/Http/Client/Adapter/Stream.php(82): Cake\Http\Client\Adapter\Stream->_send(Object(Cake\Http\Client\Request))
#2 /vendor/cakephp/cakephp/src/Http/Client.php(430): Cake\Http\Client\Adapter\Stream->send(Object(Cake\Http\Client\Request), Array)
#3 /vendor/cakephp/cakephp/src/Http/Client.php(399): Cake\Http\Client->_sendRequest(Object(Cake\Http\Client\Request), Array)
#4 /vendor/cakephp/cakephp/src/Http/Client.php(366): Cake\Http\Client->send(Object(Cake\Http\Client\Request), Array)
#5 /vendor/cakephp/cakephp/src/Http/Client.php(249): Cake\Http\Client->_doRequest('POST', 'https://account...', Array, Array)
#6 /vendor/admad/cakephp-social-auth/src/Http/Client.php(65): Cake\Http\Client->post('https://account...', Array, Array)
#7 /vendor/socialconnect/common/src/Http/Client/Client.php(58): ADmad\SocialAuth\Http\Client->request('https://account...', Array, 'POST', Array)
#8 /vendor/socialconnect/auth/src/OAuth2/AbstractProvider.php(146): SocialConnect\Common\Http\Client\Client->fromRequest(Object(SocialConnect\Common\Http\Request))
#9 /vendor/socialconnect/auth/src/OAuth2/AbstractProvider.php(190): SocialConnect\OAuth2\AbstractProvider->getAccessToken('4/AACgAJEfqjjNX...')
#10 /vendor/admad/cakephp-social-auth/src/Middleware/SocialAuthMiddleware.php(249): SocialConnect\OAuth2\AbstractProvider->getAccessTokenByRequestParameters(Array)
#11 /vendor/admad/cakephp-social-auth/src/Middleware/SocialAuthMiddleware.php(191): ADmad\SocialAuth\Middleware\SocialAuthMiddleware->_getProfile('google', Object(Cake\Http\ServerRequest))
#12 /vendor/admad/cakephp-social-auth/src/Middleware/SocialAuthMiddleware.php(152): ADmad\SocialAuth\Middleware\SocialAuthMiddleware->_handleCallbackAction(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 /vendor/cakephp/cakephp/src/Http/Runner.php(65): ADmad\SocialAuth\Middleware\SocialAuthMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 /vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 /vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#16 /vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 /vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#18 /vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#19 /vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#20 /vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#21 /vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#22 /webroot/index.php(40): Cake\Http\Server->run()
#23 {main}
```

**Comment by ADmad** [comment]
Hmm.. I'll have a look.

**Comment by BassemN** [comment]
Thanks allot.
By checking SocialConnect/common I found that they have support for Curl and Guzzle so it will be great if you added a configuration setting to allow us to choose the client for example default(CakePHP Client), Curl or Guzzle

**Comment by ADmad** [comment]
@BassemN Just wanted to let you know that this ticket has lead to https://github.com/cakephp/cakephp/pull/12209  which will land in Cake 3.7 :slightly_smiling_face:.
